config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :telefones
  resources :enderecos
  resources :contatos
  resources :tipos

end

app/models/contato.rb
class Contato < ActiveRecord::Base
  belongs_to :tipo
  has_one :endereco
  has_many :telefones
  
  accepts_nested_attributes_for :endereco
  accepts_nested_attributes_for :telefones, reject_if: :all_blank, allow_destroy: true
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
    @contato.build_endereco
    
    options_for_select
  end

  # GET /contatos/1/edit
  def edit
    options_for_select
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
  def options_for_select
    @tipo_options_for_select = Tipo.all
  end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :email, :tipo_id, :obs, 
      endereco_attributes: [:rua, :cidade, :estado],
      telefones_attributes: [:id, :telefone, :_destroy])
    end
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/contatos/_form.html.erb
<%= form_for(@contato, html: { class: "dark-matter"}) do |f| %>
  <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1>Contatos</h1>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :tipo_id %><br>
    <%= f.collection_select(:tipo_id, @tipo_options_for_select, :id, :descricao ) %>
  </div>
  
  <%= f.fields_for :endereco do |endereco_fields| %>
  <div class="field">
    <%= endereco_fields.label :rua %><br>
    <%= endereco_fields.text_field :rua %>
  </div>
  <div class="field">
    <%= endereco_fields.label :cidade %><br>
    <%= endereco_fields.text_field :cidade %>
  </div>
  <div class="field">
    <%= endereco_fields.label :estado %><br>
    <%= endereco_fields.select :estado, options_for_states(@contato.endereco.estado) %>
  </div>
   
  <% end %>  
  
  <div id="telefones">
      <%= f.fields_for :telefones do |telefones_fields| %>
          <%= render partial: "telefone_fields", locals: { f: telefones_fields} %>
      <% end %>
      <%= link_to_add_association('[Adicionar Telefone]', f, :telefones) %>
  </div>

  <div class="field">
    <%= f.label :obs %><br>
    <%= f.text_area :obs %>
  </div>
  <div class="field">
    <%= f.submit "Enviar", class:"button" %>
    <%= link_to 'Back', contatos_path, class:"button" %>

  </div>
<% end %>

app/views/contatos/_telefone_fields.html.erb
<div class="nested_fields">
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone, class: "phone-field" %>
    <%= link_to_remove_association('[remover]', f) %>
  </div>
</div>

app/views/contatos/edit.html.erb
<%= render 'form' %>

app/views/contatos/index.html.erb
<div class="dark-matter">
<p id="notice"><%= notice %></p>
<%= @contato%>
<h1>Listing Contatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
     
      <th>Tipo de Contato</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr style="background-color: <%= cycle('grey', '#555')%>">
        <td><%= contato.nome %></td>
      
        <td><%= contato.tipo.descricao %></td>
        <td><%= link_to t('buttons.show'), contato %></td>
        <td><%= link_to t('buttons.edit'), edit_contato_path(contato) %></td>
        <td><%= link_to t('buttons.destroy'), contato, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('buttons.new'), new_contato_path %>
<%= link_to 'Back', root_path, class:"button" %>
</div>

app/views/contatos/new.html.erb
<%= render 'form' %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @contato.tipo %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @contato.obs %>
</p>

<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>